"""empty message

Revision ID: 34617806e19f
Revises: 8e7ba7379127
Create Date: 2024-06-30 15:45:35.960708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34617806e19f'
down_revision = '8e7ba7379127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('email_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint('email_id', ['email_id'])

    # ### end Alembic commands ###
