"""empty message

Revision ID: 8e7ba7379127
Revises: 7bdb2486d3e6
Create Date: 2024-06-29 21:06:40.130928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7ba7379127'
down_revision = '7bdb2486d3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=80), nullable=True))
        # batch_op.create_unique_constraint("email_id", ['email_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        # batch_op.drop_constraint("email_id", type_='unique')
        batch_op.drop_column('email_id')

    # ### end Alembic commands ###
